const int obd_pids[] = {
    CALCULATED_ENGINE_LOAD,
    ENGINE_COOLANT_TEMPERATURE,
    ENGINE_RPM,
    VEHICLE_SPEED,
    AIR_INTAKE_TEMPERATURE,
    DISTANCE_TRAVELED_WITH_MIL_ON,
    DISTANCE_TRAVELED_SINCE_CODES_CLEARED,
    ENGINE_OIL_TEMPERATURE,
    TIME_SINCE_TROUBLE_CODES_CLEARED,
};
int obd_pids_length = sizeof(obd_pids) / sizeof(obd_pids[0]);